[package]
name    = "{{demo}}"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]
edition = "2018"

[dependencies]
rand       = { version = "0.7", features = [ "stdweb" ] }
num-traits = "0.2"
Inflector  = "0.11"
nalgebra   = "0.20"
ncollide3d = "0.22"
kiss3d     = "0.23"
nphysics3d = "0.14"
nphysics_testbed3d = { version = "0.8", features = [ "fluids" ] }
salva3d = { version = "0.2", features = [ "nphysics", "sampling" ] }
stdweb = "0.4"

[profile.release]
lto = true
codegen-units = 1

[[bin]]
name = "{{demo}}"
path = "./{{demo}}.rs"
